src/UTB.EShop.Web/Areas/Admin/Controllers/SecurityController.cs
using System.Web.Mvc;
using UTB.EShop.Core.CoreServices.Auth;
using UTB.EShop.Web.Areas.Admin.Models;

namespace UTB.EShop.Web.Areas.Admin.Controllers
{
	public class SecurityController : Controller
	{
		private readonly IFormAuthentication _formAuthentication;

		// CTOR
		public SecurityController(IFormAuthentication formAuthentication)
		{
			_formAuthentication = formAuthentication;
		}

		// GET: Admin/Security/Login
		public ActionResult Login()
		{
			var vm = new SecurityViewModel();
			return View(vm);
		}

		// POST: Admin/Security/Login
		[HttpPost]
		public ActionResult Login(SecurityViewModel model)
		{
			if (_formAuthentication.Authenticate(model.Login, model.Password))
			{
				return RedirectToAction("Index", "Products");
			}
			else
			{
				model.ErrorMessage = "Přihlášení se nezdařilo";
			}

			return View(model);
		}

		// GET: Admin/Security/Logout
		public RedirectToRouteResult Logout()
		{
			_formAuthentication.SignOut();

			return RedirectToAction("Login");
		}
	}
}

src/UTB.EShop.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - A5PWT [UTB]</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink(@ViewContext.RouteData.DataTokens["area"].ToString().ToUpper() + " Module", "Index", "Home", new { area = "Admin" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Products", "Index", "Products", new { area = "Admin" }, null)</li>
					<li>@Html.ActionLink("Categories", "Index", "Categories", new { area = "Admin" }, null)</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					@if(CurrentUser != null)
					{
						<li><a href="#">@CurrentUser.FirstName @CurrentUser.LastName</a></li>
					}

					@if(IsAuthenticated)
					{
						<li><a href="@Url.Action("Logout", "Security")">Logout</a></li>
					}
					<li>@Html.ActionLink("Go Eshop", "Index", "Products", new {area = "Eshop"}, null)</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>
				&copy; @DateTime.Now.Year - Roman Hanzlik -
				@Html.Raw("Area: ")<b>@ViewContext.RouteData.DataTokens["area"].ToString().ToLower()</b>@Html.Raw(",")
				@Html.Raw("Controller: ")<b>@ViewContext.RouteData.Values["controller"].ToString().ToLower()</b>@Html.Raw(",")
				@Html.Raw("Action: ")<b>@ViewContext.RouteData.Values["action"].ToString().ToLower()</b>@Html.Raw("<!-- Commentem resim whitespace mezi tagy")
				@if (Url.RequestContext.RouteData.Values["id"] != null)
				{
					@Html.Raw("-->, Id: ")<b>@Url.RequestContext.RouteData.Values["id"]</b>
				}
				else
				{
					@Html.Raw("-->")
				}
			</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>