src/UTB.EShop.Web/Areas/Eshop/Models/CartViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using UTB.EShop.Core.Models.Carts;

namespace UTB.EShop.Web.Areas.Eshop.Models
{
	public class CartViewModel
	{
		public Cart Cart { get; set; }
		public IEnumerable<SelectListItem> Payments { get; set; }
		public IEnumerable<SelectListItem> Deliveries { get; set; }
		public int CurrentStep { get; set; }
	}
}

src/UTB.EShop.Web/Areas/Admin/Controllers/ProductsController.cs
using System.Web.Mvc;
using UTB.EShop.Core.Models.Users;
using UTB.EShop.Core.Mvc.Permissions;
using UTB.EShop.Web.Areas.Admin.AppServices.Products;
using UTB.EShop.Web.Areas.Admin.Models;

namespace UTB.EShop.Web.Areas.Admin.Controllers
{
	[Authorize]
	public class ProductsController : Controller
	{
		private readonly IProductAppService _productAppService;

		// CTOR
		public ProductsController(IProductAppService productAppService)
		{
			_productAppService = productAppService;
		}

		// GET: Admin/Products
		[HttpGet]
		public ViewResult Index()
		{
			var vm = _productAppService.GetAllViewModel();

			return View(vm);
		}

		[HttpGet]
		[HasAccessRole(Roles.Admin)]
		public ViewResult Create()
		{
			var vm = _productAppService.GetViewModel(null);

			return View();
		}

		[HttpPost]
		public ActionResult Create(ProductViewModel vm)
		{
			if (!ModelState.IsValid)
			{
				return View(vm);
			}

			_productAppService.Insert(vm);

			return RedirectToAction("Index");
		}

		[HttpGet]
		[HasAccessRole(Roles.Manager)]
		public ActionResult Edit(int productID)
		{
			var vm = _productAppService.GetViewModel(productID);

			if (vm.Product == null)
			{
				return RedirectToAction("Error404", "Error");
			}

			return View(vm);
		}

		[HttpPost]
		public RedirectToRouteResult Edit(ProductViewModel vm)
		{
			_productAppService.Update(vm);

			return RedirectToAction("Index");
		}

		[HttpGet]
		public RedirectToRouteResult Delete(int productID)
		{
			_productAppService.Delete(productID);

			return RedirectToAction("Index");
		}

		[HttpPost]
		public RedirectToRouteResult InsertOrRemoveCategories(ProductViewModel vm)
		{
			_productAppService.InsertOrRemoveProductIntoOrFromCategories(vm);

			return RedirectToAction("Index");
		}
	}
}

src/UTB.EShop.Web/Areas/Eshop/Controllers/CartController.cs
using System.Web.Mvc;
using UTB.EShop.Web.Areas.Eshop.AppServices.Carts;
using UTB.EShop.Web.Areas.Eshop.Models;

namespace UTB.EShop.Web.Areas.Eshop.Controllers
{
	public class CartController : Controller
	{
		private readonly ICartAppService _cartAppService;

		public CartController(ICartAppService cartAppService)
		{
			_cartAppService = cartAppService;
		}

		// GET: Eshop/Cart
		public ActionResult Index()
		{
			var vm = _cartAppService.GetViewModel();

			return View(vm);
		}

		[HttpPost]
		public JsonResult AddToCart(int productID, int amount)
		{
			var cartItem = _cartAppService.AddToCart(productID, amount);

			return Json(new
			{
				cartItem.CartID,
				cartItem.CartItemID,
				cartItem.ProductID,
				cartItem.Amount
			});
		}

		[HttpPost]
		public JsonResult RemoveFromCart(int productID)
		{
			_cartAppService.RemoveFromCart(productID);

			return Json(string.Empty);
		}

		// STEPs
		[HttpGet]
		public ActionResult Step1()
		{
			var vm = _cartAppService.GetViewModel(1);

			return View(vm);
		}

		[HttpPost]
		public ActionResult Step1(CartViewModel vm)
		{
			if (!ModelState.IsValid)
			{
				return View(vm);
			}

			_cartAppService.InsertAddresses(vm);

			return RedirectToAction("Step2");
		}

		[HttpGet]
		public ActionResult Step2()
		{
			var vm = _cartAppService.GetViewModel(2);

			return View(vm);
		}

		[HttpPost]
		public ActionResult Step2(CartViewModel vm)
		{
			if (!ModelState.IsValid)
			{
				return View(vm);
			}

			_cartAppService.InsertPaymentAndDelivery(vm);

			return RedirectToAction("Step3");
		}

		[HttpGet]
		public ActionResult Step3()
		{
			var vm = _cartAppService.GetViewModel(3);

			return View(vm);
		}
	}
}

src/UTB.EShop.Web/Areas/Eshop/Controllers/OrderController.cs
using System.Web.Mvc;
using UTB.EShop.Web.Areas.Eshop.AppServices.Orders;

namespace UTB.EShop.Web.Areas.Eshop.Controllers
{
    public class OrderController : Controller
    {
	    private readonly IOrderAppService _orderAppService;

	    public OrderController(IOrderAppService orderAppService)
	    {
		    _orderAppService = orderAppService;
	    }

	    public RedirectToRouteResult Create()
	    {
		    _orderAppService.CreateOrderFromCart();

		    return RedirectToAction("Success");
	    }

	    public ViewResult Success()
	    {
		    return View();
	    }
	}
}

src/UTB.EShop.Web/Areas/Eshop/Views/Cart/Index.cshtml
﻿@model UTB.EShop.Web.Areas.Eshop.Models.CartViewModel

<h1 class="nadpis-h1-web">Košík</h1>

<div class="row">
	@if (Model.Cart.CartItems.Any())
	{
		<div class="col-xs-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Název produktu</th>
						<th>Počet</th>
						<th>Cena / ks</th>
						<th>Cena celkem</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Total</th>
						<th></th>
						<th></th>
						<th>
							@Model.Cart.TotalPrice.ToString("C2")
						</th>
					</tr>
				</tfoot>
				<tbody>
					@foreach (var item in Model.Cart.CartItems)
					{
						<tr data-productid="@item.ProductID">
							<td>@item.Product.Name</td>
							<td>@Html.TextBox("Amount", item.Amount, new { type = "number", min = "0", @class = "amount" })</td>
							<td>@item.Product.Price.ToString("C2")</td>
							<td>@((item.Amount * item.Product.Price).ToString("C2"))</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
		<div class="col-xs-12 text-left">
			<table class="table table-striped">
				<tr>
					<td class="text-left">
						@Html.ActionLink("Zpět", "Index", "Products", new { area = "Eshop" }, new { @class = "btn btn-primary" })
					</td>
					<td class="text-right">
						@Html.ActionLink("Další krok", "Step1", "Cart", new { area = "Eshop" }, new { @class = "btn btn-primary" })
					</td>
				</tr>
			</table>
		</div>
	}
	else
	{
		<div class="col-xs-12">
			<span>Váš košík je prázdný</span>
		</div>
	}
</div>

@section scripts {
	<script type="text/javascript">
		$(document).ready(function () {
			$('input.amount').change(function () {
				var $self = $(this),
					productID = $self.closest('tr').data('productid'),
					amount = parseInt($self.val());

				if (amount === 0) {
					deleteFromCart(productID);
				} else {
					changeAmountInCart(productID, amount);
				}
			});

			function deleteFromCart(productID) {
				$.ajax({
					url: '@Url.Action("RemoveFromCart", "Cart", new { area = "EShop" })',
					type: 'POST',
					data: { productID: productID },
					success: function() {
						location.reload();
					},
					error: function() {
						alert('Při mazání nastala chyba');
					}
				});
			}

			function changeAmountInCart(productID, amount) {
				$.ajax({
					url: '@Url.Action("AddToCart", "Cart", new { area = "EShop" })',
					type: 'POST',
					data: { productID: productID, amount: amount },
					success: function() {
						location.reload();
					},
					error: function() {
						alert('Chyba při změně kusů.');
					}
				});
			}
		});
	</script>
}

src/UTB.EShop.Web/Areas/Eshop/Views/Cart/Step1.cshtml
@using UTB.EShop.Core.Models.Addresses
@using UTB.EShop.Core.Models.Carts
﻿@model UTB.EShop.Web.Areas.Eshop.Models.CartViewModel

@{
	ViewBag.Title = "Step 1 - Addresses";
}

<h1 class="nadpis-h1-web">Adresy</h1>

<div class="row">
	@using (Html.BeginForm("Step1", "Cart", new { area = "EShop" }, FormMethod.Post))
	{
		@Html.HiddenFor(m => m.CurrentStep)

		<div class="col-xs-6">
			<h4>Billing Address</h4>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.BillingAddress)}.{nameof(Address.FirstName)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.BillingAddress.FirstName, "Jméno", new {@class = "col-xs-3 control-label required"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.FirstName, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.BillingAddress.FirstName)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.BillingAddress)}.{nameof(Address.LastName)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.BillingAddress.LastName, "Příjmení", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.LastName, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.BillingAddress.LastName)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.BillingAddress)}.{nameof(Address.Street)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.BillingAddress.Street, "Ulice", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.Street, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.BillingAddress.Street)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.BillingAddress)}.{nameof(Address.StreetNo)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.BillingAddress.StreetNo, "Číslo popisné", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.StreetNo, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.BillingAddress.StreetNo)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.BillingAddress)}.{nameof(Address.City)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.BillingAddress.City, "Město", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.City, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.BillingAddress.City)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.BillingAddress)}.{nameof(Address.PostalCode)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.BillingAddress.PostalCode, "PSČ", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.PostalCode, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.BillingAddress.PostalCode)
				</div>
			</div>
		</div>

		<div class="col-xs-6">
			<h4>Delivery Address</h4>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.ShippingAddress)}.{nameof(Address.FirstName)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.ShippingAddress.FirstName, "Jméno", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.FirstName, new {@class = "form-control"})
					@Html.ValidationMessageFor(m => m.Cart.ShippingAddress.FirstName)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.ShippingAddress)}.{nameof(Address.LastName)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.ShippingAddress.LastName, "Příjmení", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.LastName, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.Cart.ShippingAddress.LastName)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.ShippingAddress)}.{nameof(Address.Street)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.ShippingAddress.Street, "Ulice", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.Street, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.Cart.ShippingAddress.Street)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.ShippingAddress)}.{nameof(Address.StreetNo)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.ShippingAddress.StreetNo, "Číslo popisné", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.StreetNo, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.Cart.ShippingAddress.StreetNo)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.ShippingAddress)}.{nameof(Address.City)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.ShippingAddress.City, "Město", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.City, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.Cart.ShippingAddress.City)
				</div>
			</div>

			<div class="form-group @(!ViewData.ModelState.IsValidField($"{nameof(Cart)}.{nameof(Cart.ShippingAddress)}.{nameof(Address.PostalCode)}") ? "has-error" : "")">
				@Html.LabelFor(m => m.Cart.ShippingAddress.PostalCode, "PSČ", new {@class = "col-xs-3 control-label"})
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.PostalCode, new { @class = "form-control" })
					@Html.ValidationMessageFor(m => m.Cart.ShippingAddress.PostalCode)
				</div>
			</div>
		</div>

		<div class="col-xs-12 text-left">
			<table class="table table-striped">
				<tr>
					<td class="text-left">
						@Html.ActionLink("Zpět", "Index", "Cart", new { area = "Eshop" }, new { @class = "btn btn-primary" })
					</td>
					<td class="text-right">
						<button type="submit" class="btn btn-primary">Další krok</button>
					</td>
				</tr>
			</table>
		</div>
	}
</div>

src/UTB.EShop.Web/Areas/Eshop/Views/Cart/Step2.cshtml
﻿@model UTB.EShop.Web.Areas.Eshop.Models.CartViewModel

@{
	ViewBag.Title = "Step 2 (Payment & Delivery Options)";
}

<h1 class="nadpis-h1-web">Platba & Doprava</h1>

<div class="row">
	@using (Html.BeginForm("Step2", "Cart", new { area = "EShop" }, FormMethod.Post))
	{
		@Html.HiddenFor(m => m.CurrentStep)

		<div class="col-xs-12">
			<div class="form-group">
				@Html.LabelFor(m => m.Cart.PaymentID, "Platba", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.DropDownListFor(m => m.Cart.PaymentID, Model.Payments, new { @class = "form-control" })
				</div>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="form-group">
				@Html.LabelFor(m => m.Cart.DeliveryID, "Způsob doručení", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.DropDownListFor(m => m.Cart.DeliveryID, Model.Deliveries, new { @class = "form-control" })
				</div>
			</div>
		</div>

		<div class="col-xs-12 text-left">
			<table class="table table-striped">
				<tr>
					<td class="text-left">
						@Html.ActionLink("Zpět", "Step1", "Cart", new { area = "Eshop" }, new { @class = "btn btn-primary" })
					</td>
					<td class="text-right">
						<button type="submit" class="btn btn-primary">Další krok</button>
					</td>
				</tr>
			</table>
		</div>
	}
</div>

src/UTB.EShop.Web/Areas/Eshop/Views/Cart/Step3.cshtml
@using UTB.EShop.Web.Areas.Admin.Controllers
﻿@model UTB.EShop.Web.Areas.Eshop.Models.CartViewModel

@{
	ViewBag.Title = "Step 3 (Overview)";
}

<h1 class="nadpis-h1-web">Overview</h1>

<div class="row">
	@if (Model.Cart.UserTrackingCode.Any())
	{
		@Html.HiddenFor(m => m.CurrentStep)

		<div class="col-xs-6">
			<!-- Billing Address : BEGIN -->
			<h4>Billing Address</h4>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.BillingAddress.FirstName, "Jméno", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.FirstName, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.BillingAddress.LastName, "Příjmení", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.LastName, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.BillingAddress.Street, "Ulice", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.Street, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.BillingAddress.StreetNo, "Číslo popisné", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.StreetNo, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.BillingAddress.City, "Město", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.City, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.BillingAddress.PostalCode, "PSČ", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.BillingAddress.PostalCode, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>
		</div>
		<!-- Billing Address : END -->

		<!-- Delivery Address : BEGIN -->
		<div class="col-xs-6">
			<h4>Delivery Address</h4>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.ShippingAddress.FirstName, "Jméno", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.FirstName, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.ShippingAddress.LastName, "Příjmení", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.LastName, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.ShippingAddress.Street, "Ulice", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.Street, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.ShippingAddress.StreetNo, "Číslo popisné", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.StreetNo, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.ShippingAddress.City, "Město", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.City, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Cart.ShippingAddress.PostalCode, "PSČ", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Cart.ShippingAddress.PostalCode, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>
		</div>
		<!-- Delivery Address : END -->

		<!-- Payment Method : BEGIN -->
		<div class="col-xs-6">
			<h4>Payment Method</h4>
			<div class="form-group">
				@Html.LabelFor(m => m.Cart.PaymentID, "Platba", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Payments.Where(p => p.Value == m.Cart.PaymentID.ToString()).First().Text, new { @class = "form-control", @readonly = "readonly" })
				</div>
			</div>
		</div>
		<!-- Payment Method : END -->

		<!-- Delivery Method : BEGIN -->
		<div class="col-xs-6">
			<h4>Delivery Method</h4>
			<div class="form-group">
				@Html.LabelFor(m => m.Cart.DeliveryID, "Způsob doručení", new { @class = "col-xs-3 control-label" })
				<div class="col-xs-9">
					@Html.TextBoxFor(m => m.Deliveries.Where(p => p.Value == m.Cart.DeliveryID.ToString()).First().Text, new { @class = "form-control", @readonly = "readonly" })

				</div>
			</div>
		</div>
		<!-- Delivery Method : END -->

		<!-- Cart : BEGIN -->
		<div class="col-xs-12">
			<h4>Products</h4>
			@if (Model.Cart.CartItems.Any())
			{
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Název produktu</th>
							<th>Počet</th>
							<th>Cena / ks</th>
							<th>Cena celkem</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Total</th>
							<th></th>
							<th></th>
							<th>
								@Model.Cart.TotalPrice.ToString("C2")
							</th>
						</tr>
					</tfoot>
					<tbody>
						@foreach (var item in Model.Cart.CartItems)
						{
							<tr data-productid="@item.ProductID">
								<td>@item.Product.Name</td>
								<td>@item.Amount</td>
								<td>@item.Product.Price.ToString("C2")</td>
								<td>@((item.Amount * item.Product.Price).ToString("C2"))</td>
							</tr>
						}
					</tbody>
				</table>
			}
			else
			{
				<div class="col-xs-12">
					<span>Váš košík je prázdný</span>
				</div>
			}
		</div>

		<!-- LINKS : BEGIN -->
		<div class="col-xs-12 text-left">
			<table class="table table-striped">
				<tr>
					<td class="text-left">
						@Html.ActionLink("Zpět", "Step2", "Cart", new { area = "Eshop" }, new { @class = "btn btn-primary" })
					</td>
					@if (Model.Cart.CartItems.Any())
					{
						<td class="text-right">
							@Html.ActionLink("Objednat", "Create", "Order", new { area = "Eshop" }, new { @class = "btn btn-primary" })
						</td>
					}
					else
					{
						<td class="text-right">
							@Html.ActionLink("Objednat", "Create", "Order", new { area = "Eshop" }, new { @class = "btn btn-primary disabled" })
						</td>
					}
				</tr>
			</table>
		</div>
		<!-- LINKS : END -->
	}
	else
	{
		<span>Sorry nemam kosik.</span>
	}
</div>