src/UTB.EShop.Web/Areas/Admin/Models/CategoriesViewModel.cs
using System.Collections.Generic;
using UTB.EShop.Core.Models.Categories;

namespace UTB.EShop.Web.Areas.Admin.Models
{
	public class CategoriesViewModel
	{
		public IList<Category> Categories { get; set; }
	}
}

src/UTB.EShop.Web/Areas/Admin/Models/CategoryViewModel.cs
using UTB.EShop.Core.Models.Categories;

namespace UTB.EShop.Web.Areas.Admin.Models
{
	public class CategoryViewModel
	{
		public Category Category { get; set; }
	}
}

src/UTB.EShop.Web/Areas/Admin/Controllers/CategoriesController.cs
using System.Web.Mvc;
using UTB.EShop.Web.Areas.Admin.AppServices.Categories;
using UTB.EShop.Web.Areas.Admin.Models;

namespace UTB.EShop.Web.Areas.Admin.Controllers
{
	[Authorize]
	public class CategoriesController : Controller
    {
	    private readonly ICategoryAppService _categoryAppService;

	    public CategoriesController(ICategoryAppService categoryAppService)
	    {
		    _categoryAppService = categoryAppService;
	    }

		// GET: Admin/Categories
		[HttpGet]
		public ActionResult Index()
	    {
		    var vm = _categoryAppService.GetAllViewModel();

		    return View(vm);
	    }

	    [HttpGet]
	    public ViewResult Create()
	    {
		    var vm = _categoryAppService.GetViewModel(null);

		    return View(vm);
	    }

	    [HttpPost]
	    public RedirectToRouteResult Create(CategoryViewModel vm)
	    {
		    _categoryAppService.Insert(vm);

		    return RedirectToAction("Index");
	    }

		[HttpGet]
		public ViewResult Edit(int categoryID)
	    {
		    var vm = _categoryAppService.GetViewModel(categoryID);

		    return View(vm);
	    }

	    [HttpPost]
	    public RedirectToRouteResult Edit(CategoryViewModel vm)
	    {
		    _categoryAppService.Update(vm);

		    return RedirectToAction("Index");
	    }

		[HttpGet]
	    public RedirectToRouteResult Delete(int categoryID)
	    {
		    _categoryAppService.Delete(categoryID);

		    return RedirectToAction("Index");
	    }
	}
}

src/UTB.EShop.Web/Areas/Admin/Views/Categories/Create.cshtml
﻿@model UTB.EShop.Web.Areas.Admin.Models.CategoryViewModel

@{
	ViewBag.Title = "Nová kategorie";
}

<div class="row">
	<div class="col-xs-12">
		@using (Html.BeginForm("Create", "Categories", new { area = "Admin" }, FormMethod.Post, new { @class = "form-horizontal" }))
		{
			<div class="form-group">
				@Html.LabelFor(m => m.Category.Name, "Jméno", new { @class = "col-xs-2 control-label" })
				<div class="col-xs-10">
					@Html.TextBoxFor(m => m.Category.Name, new { @class = "form-control" })
				</div>
			</div>
    
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<a class="btn btn-default" href="@Url.Action("Index", "Categories")">Zpět</a>
					<button type="submit" class="btn btn-primary">Uložit</button>
				</div>
			</div>
		}
	</div>
</div>

src/UTB.EShop.Web/Areas/Admin/Views/Categories/Edit.cshtml
@model UTB.EShop.Web.Areas.Admin.Models.CategoryViewModel

@{
	ViewBag.Title = "Úprava kategorie";
}

<div class="row">
	<div class="col-xs-12">
		@using (Html.BeginForm("Edit", "Categories", new { area = "Admin" }, FormMethod.Post, new { @class = "form-horizontal" }))
		{
			@Html.HiddenFor(e => e.Category.CategoryID)

			<div class="form-group">
				@Html.LabelFor(m => m.Category.CategoryID, "ID", new { @class = "col-xs-2 control-label" })
				<div class="col-xs-10">
					@Html.TextBoxFor(m => m.Category.CategoryID, new { @class = "form-control", disabled = "disabled" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.Category.Name, "Název", new { @class = "col-xs-2 control-label" })
				<div class="col-xs-10">
					@Html.TextBoxFor(m => m.Category.Name, new { @class = "form-control" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<a class="btn btn-default" href="@Url.Action("Index", "Categories")">Zpět</a>
					<button type="submit" class="btn btn-primary">Uložit</button>
				</div>
			</div>
		}
	</div>
</div>

src/UTB.EShop.Web/Areas/Admin/Views/Categories/Index.cshtml
@model UTB.EShop.Web.Areas.Admin.Models.CategoriesViewModel

@{
	ViewBag.Title = "Kategorie";
}

<div class="row">
	<div class="col-xs-12">
		<table class="table table-striped">
			<thead>
				<tr>
					<td>ID</td>
					<td>Název</td>
					<td></td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				@foreach (var category in Model.Categories)
				{
					<tr>
						<td>
							<span>@category.CategoryID</span>
						</td>
						<td>
							<span>@category.Name</span>
						</td>
						<td>
							<a href="@Url.Action("Edit", "Categories", new {categoryID = category.CategoryID})">
								<i class="glyphicon glyphicon-edit"></i>
							</a>
						</td>
						<td>
							<a href="@Url.Action("Delete", "Categories", new {categoryID = category.CategoryID})">
								<i class="glyphicon glyphicon-remove"></i>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
	<div class="col-xs-12">
		@Html.ActionLink("Přidat", "Create", "Categories", new { area = "Admin" }, new { @class = "btn btn-primary" })
	</div>
</div>